const mongoose = require('mongoose');

const userSettingsSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      unique: true,
      index: true,
    },
    account: {
      fullName: { type: String, default: '' },
      username: { type: String, default: '' },
      email: { type: String, default: '' },
      phone: { type: String, default: '' },
      dateOfBirth: { type: String, default: '' },
      bio: { type: String, default: '' },
      headline: { type: String, default: '' },
      occupation: { type: String, default: '' },
      education: { type: String, default: '' },
      college: { type: String, default: '' },
      website: { type: String, default: '' },
      location: { type: String, default: '' },
      timezone: { type: String, default: 'UTC+05:30 (Asia/Kolkata)' },
      language: { type: String, default: 'en' },
      country: { type: String, default: 'India' },
      socialLinks: {
        github: { type: String, default: '' },
        linkedin: { type: String, default: '' },
        twitter: { type: String, default: '' },
      },
    },
    profile: {
      avatarUrl: { type: String, default: '' },
      coverImageUrl: { type: String, default: '' },
      portfolioUrl: { type: String, default: '' },
      resumeUrl: { type: String, default: '' },
      skills: [{ type: String }],
      interests: [{ type: String }],
      achievements: [{ type: String }],
      visibility: { type: String, enum: ['public', 'private', 'friends'], default: 'public' },
    },
    security: {
      twoFactorEnabled: { type: Boolean, default: false },
      twoFactorMethod: { type: String, enum: ['authenticator', 'sms', 'email'], default: 'authenticator' },
      recoveryEmail: { type: String, default: '' },
      recoveryPhone: { type: String, default: '' },
      loginAlerts: { type: Boolean, default: true },
      suspiciousDetection: { type: Boolean, default: true },
      securityScore: { type: Number, default: 85 },
    },
    privacy: {
      profileVisibility: { type: String, enum: ['public', 'private'], default: 'public' },
      hideEmail: { type: Boolean, default: true },
      hidePhone: { type: Boolean, default: true },
      hideActivity: { type: Boolean, default: false },
      hideProgress: { type: Boolean, default: false },
      hideCertificates: { type: Boolean, default: false },
      hideAchievements: { type: Boolean, default: false },
      hideProjects: { type: Boolean, default: false },
      messagePermission: { type: String, enum: ['everyone', 'connections', 'nobody'], default: 'everyone' },
      followPermission: { type: String, enum: ['everyone', 'nobody'], default: 'everyone' },
      blockedUserIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
      mutedUserIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    },
    notifications: {
      emailNotifs: { type: Boolean, default: true },
      pushNotifs: { type: Boolean, default: true },
      smsNotifs: { type: Boolean, default: false },
      browserNotifs: { type: Boolean, default: true },
      communityNotifs: { type: Boolean, default: true },
      learningNotifs: { type: Boolean, default: true },
      assessmentNotifs: { type: Boolean, default: true },
      liveSessionNotifs: { type: Boolean, default: true },
      resourceNotifs: { type: Boolean, default: true },
      hackathonNotifs: { type: Boolean, default: true },
      aiNotifs: { type: Boolean, default: true },
      marketingEmails: { type: Boolean, default: false },
      weeklyDigest: { type: Boolean, default: true },
    },
    appearance: {
      theme: { type: String, enum: ['light', 'dark', 'system'], default: 'dark' },
      accentColor: { type: String, default: '#04AA6D' }, // CodeSphere Emerald Green
      sidebarStyle: { type: String, enum: ['default', 'compact'], default: 'default' },
      compactMode: { type: Boolean, default: false },
      fontSize: { type: String, enum: ['small', 'medium', 'large'], default: 'medium' },
      cardStyle: { type: String, enum: ['glass', 'flat', 'bordered'], default: 'glass' },
      animationEnabled: { type: Boolean, default: true },
      reduceMotion: { type: Boolean, default: false },
      layoutDensity: { type: String, enum: ['comfortable', 'compact'], default: 'comfortable' },
    },
    accessibility: {
      screenReaderSupport: { type: Boolean, default: false },
      keyboardNavigation: { type: Boolean, default: true },
      highContrastMode: { type: Boolean, default: false },
      colorBlindMode: { type: String, enum: ['none', 'protanopia', 'deuteranopia', 'tritanopia'], default: 'none' },
      largeText: { type: Boolean, default: false },
      captionsEnabled: { type: Boolean, default: true },
      audioDescriptions: { type: Boolean, default: false },
    },
    languageRegion: {
      language: { type: String, default: 'English (US)' },
      country: { type: String, default: 'India' },
      dateFormat: { type: String, default: 'DD/MM/YYYY' },
      timeFormat: { type: String, default: '12-hour (AM/PM)' },
      timezone: { type: String, default: 'Asia/Kolkata (GMT+5:30)' },
      currency: { type: String, default: 'INR (₹)' },
    },
    learning: {
      preferredTechnologies: [{ type: String }],
      learningGoals: { type: String, default: 'Full Stack Web Development & AI Architect' },
      dailyStudyTargetMinutes: { type: Number, default: 60 },
      weeklyGoalHours: { type: Number, default: 10 },
      preferredDifficulty: { type: String, enum: ['beginner', 'intermediate', 'advanced'], default: 'intermediate' },
      preferredStyle: { type: String, enum: ['video', 'hands_on', 'text'], default: 'hands_on' },
      autoContinueCourses: { type: Boolean, default: true },
      autoSaveProgress: { type: Boolean, default: true },
      learningReminders: { type: Boolean, default: true },
    },
    coding: {
      preferredLanguage: { type: String, default: 'javascript' },
      editorTheme: { type: String, default: 'vs-dark' },
      tabSize: { type: Number, default: 2 },
      fontFamily: { type: String, default: "'Fira Code', monospace" },
      fontSize: { type: Number, default: 14 },
      autoSave: { type: String, enum: ['off', 'afterDelay', 'onFocusChange'], default: 'afterDelay' },
      wordWrap: { type: Boolean, default: true },
      codeFormatting: { type: Boolean, default: true },
      autosuggestion: { type: Boolean, default: true },
      terminalTheme: { type: String, default: 'dark' },
      compilerDefaults: { type: String, default: 'es2022' },
    },
    ai: {
      enableAI: { type: Boolean, default: true },
      aiPersonality: { type: String, enum: ['encouraging', 'concise', 'strict_mentor', 'expert_architect'], default: 'expert_architect' },
      responseStyle: { type: String, enum: ['detailed', 'bullet_points', 'code_first'], default: 'code_first' },
      creativityLevel: { type: Number, default: 0.7 },
      codingAssistant: { type: Boolean, default: true },
      aiTutor: { type: Boolean, default: true },
      aiCodeReview: { type: Boolean, default: true },
      aiSuggestions: { type: Boolean, default: true },
      dailyLimitCredits: { type: Number, default: 250 },
    },
    dashboard: {
      widgetsOrder: [{ type: String }],
      hiddenWidgets: [{ type: String }],
      favoriteWidgets: [{ type: String }],
      defaultLayout: { type: String, enum: ['standard', 'compact', 'analytics'], default: 'standard' },
    },
    calendar: {
      googleSync: { type: Boolean, default: false },
      outlookSync: { type: Boolean, default: false },
      appleSync: { type: Boolean, default: false },
      syncSessions: { type: Boolean, default: true },
      syncEvents: { type: Boolean, default: true },
      reminderLeadTimeMinutes: { type: Number, default: 15 },
    },
    integrations: {
      githubConnected: { type: Boolean, default: false },
      vsCodeConnected: { type: Boolean, default: true },
      discordConnected: { type: Boolean, default: false },
      slackConnected: { type: Boolean, default: false },
      googleDriveConnected: { type: Boolean, default: false },
      notionConnected: { type: Boolean, default: false },
      figmaConnected: { type: Boolean, default: false },
    },
    experimental: {
      betaFeatures: { type: Boolean, default: true },
      aiBeta: { type: Boolean, default: true },
      labs: { type: Boolean, default: false },
      earlyAccess: { type: Boolean, default: true },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('UserSettings', userSettingsSchema);
