const fs = require("fs");
const path = require("path");

const SEEDED_NOTES = [
  {
    "_id": "6a7ad242e3d2c3755532ca9e",
    "title": "CSS3 Complete Master Notes & Cheat Sheet",
    "description": "Master Cascading Style Sheets (CSS3) from basic selectors, box model, and Flexbox/Grid layouts to keyframe animations and responsive design.",
    "thumbnail": "",
    "category": "Full Stack & Web Dev",
    "subCategory": "",
    "difficulty": "beginner",
    "tags": [
      "css",
      "css3",
      "frontend",
      "web-dev",
      "cheatsheet",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/CSS_Complete_Notes.pdf",
    "externalUrl": "/mock-resources-proxy/CSS_Complete_Notes.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 340,
    "downloadsCount": 195,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.9,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.736Z",
    "updatedAt": "2026-08-11T07:41:54.736Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532ca9f",
    "title": "DSA Complete Notes & Algorithms Handbook",
    "description": "Comprehensive Data Structures & Algorithms handbook covering Arrays, Linked Lists, Stacks, Queues, Trees, Graphs, Sorting, DP, and LeetCode patterns.",
    "thumbnail": "",
    "category": "DSA & Algorithms",
    "subCategory": "",
    "difficulty": "intermediate",
    "tags": [
      "dsa",
      "algorithms",
      "data-structures",
      "leetcode",
      "cpp",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/DSA_CompleteNotes.pdf",
    "externalUrl": "/mock-resources-proxy/DSA_CompleteNotes.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 520,
    "downloadsCount": 310,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 5,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.737Z",
    "updatedAt": "2026-08-11T07:41:54.737Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa0",
    "title": "HTML5 Complete Handbook & Reference",
    "description": "HTML5 complete developer reference guide covering modern semantic elements, input controls, canvas, audio/video, and web accessibility standards.",
    "thumbnail": "",
    "category": "Full Stack & Web Dev",
    "subCategory": "",
    "difficulty": "beginner",
    "tags": [
      "html",
      "html5",
      "frontend",
      "web-dev",
      "cheatsheet",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/HTML_Complete_Notes.pdf",
    "externalUrl": "/mock-resources-proxy/HTML_Complete_Notes.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 290,
    "downloadsCount": 165,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.8,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.737Z",
    "updatedAt": "2026-08-11T07:41:54.737Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa1",
    "title": "JavaScript Chapterwise Complete Notes",
    "description": "Detailed chapterwise JavaScript guide from fundamentals, DOM manipulation, ES6+ features, and closures to Promises, Async/Await, and Event Loop.",
    "thumbnail": "",
    "category": "Full Stack & Web Dev",
    "subCategory": "",
    "difficulty": "beginner",
    "tags": [
      "javascript",
      "js",
      "frontend",
      "es6",
      "cheatsheet",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/JS_Chapterwise_Notes.pdf",
    "externalUrl": "/mock-resources-proxy/JS_Chapterwise_Notes.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 610,
    "downloadsCount": 420,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.9,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.737Z",
    "updatedAt": "2026-08-11T07:41:54.737Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa2",
    "title": "Java Complete Mastery Notes & Handbook",
    "description": "Complete Object-Oriented Programming in Java reference manual covering OOPs principles, Collections Framework, Multithreading, JVM, and Exception handling.",
    "thumbnail": "",
    "category": "General CS",
    "subCategory": "",
    "difficulty": "intermediate",
    "tags": [
      "java",
      "oops",
      "backend",
      "collections",
      "cheatsheet",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/Java_Complete_Notes.pdf",
    "externalUrl": "/mock-resources-proxy/Java_Complete_Notes.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 480,
    "downloadsCount": 285,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.9,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.738Z",
    "updatedAt": "2026-08-11T07:41:54.738Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa3",
    "title": "Flask Web Framework Complete Cheatsheet",
    "description": "Quick reference for Python Flask micro-framework: routing, request handling, Jinja2 templating, ORM database integration, and REST APIs.",
    "thumbnail": "",
    "category": "AI, ML & Data Science",
    "subCategory": "",
    "difficulty": "beginner",
    "tags": [
      "python",
      "flask",
      "backend",
      "cheatsheet",
      "api",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/Flask%20Cheatsheet.pdf",
    "externalUrl": "/mock-resources-proxy/Flask%20Cheatsheet.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 230,
    "downloadsCount": 140,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.7,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.738Z",
    "updatedAt": "2026-08-11T07:41:54.738Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa4",
    "title": "PHP Backend Scripting Complete Cheatsheet",
    "description": "PHP backend web development cheatsheet covering syntax, superglobals, sessions, PDO database queries, and server-side forms processing.",
    "thumbnail": "",
    "category": "Full Stack & Web Dev",
    "subCategory": "",
    "difficulty": "beginner",
    "tags": [
      "php",
      "backend",
      "web-dev",
      "cheatsheet",
      "notes"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "/mock-resources-proxy/Php%20Cheatsheet.pdf",
    "externalUrl": "/mock-resources-proxy/Php%20Cheatsheet.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 195,
    "downloadsCount": 110,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.6,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.738Z",
    "updatedAt": "2026-08-11T07:41:54.738Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa5",
    "title": "Python Pandas & Data Analysis Reference",
    "description": "Official cheat sheet for Python Pandas library covering DataFrames, Series, filtering, grouping, merging, and data manipulation.",
    "thumbnail": "",
    "category": "AI, ML & Data Science",
    "subCategory": "",
    "difficulty": "intermediate",
    "tags": [
      "python",
      "pandas",
      "data-science",
      "analytics"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf",
    "externalUrl": "https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 310,
    "downloadsCount": 205,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.8,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.738Z",
    "updatedAt": "2026-08-11T07:41:54.738Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa6",
    "title": "PyTorch & Deep Learning Foundations",
    "description": "Foundational research paper and architecture guide for deep learning, PyTorch neural networks, and modern transformer models.",
    "thumbnail": "",
    "category": "AI, ML & Data Science",
    "subCategory": "",
    "difficulty": "advanced",
    "tags": [
      "pytorch",
      "deep-learning",
      "ai",
      "neural-networks"
    ],
    "language": "English",
    "resourceType": "pdf",
    "fileUrl": "https://cdn.openai.com/papers/gpt-4.pdf",
    "externalUrl": "https://cdn.openai.com/papers/gpt-4.pdf",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 450,
    "downloadsCount": 290,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.9,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.739Z",
    "updatedAt": "2026-08-11T07:41:54.739Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa7",
    "title": "Full-Stack MERN Starter & Auth Template",
    "description": "Production-ready MERN stack boilerplate with JWT authentication, role-based authorization, MongoDB Mongoose models, and React UI components.",
    "thumbnail": "",
    "category": "Full Stack & Web Dev",
    "subCategory": "",
    "difficulty": "intermediate",
    "tags": [
      "react",
      "node",
      "express",
      "mongodb",
      "mern"
    ],
    "language": "English",
    "resourceType": "source_code",
    "fileUrl": "https://github.com/facebook/react",
    "externalUrl": "https://github.com/facebook/react",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 740,
    "downloadsCount": 510,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 5,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.739Z",
    "updatedAt": "2026-08-11T07:41:54.739Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa8",
    "title": "LangChain & RAG AI Architecture Boilerplate",
    "description": "Open-source framework for building LLM applications, retrieval-augmented generation (RAG), vector store embeddings, and AI agents.",
    "thumbnail": "",
    "category": "AI, ML & Data Science",
    "subCategory": "",
    "difficulty": "advanced",
    "tags": [
      "langchain",
      "rag",
      "llm",
      "ai",
      "python"
    ],
    "language": "English",
    "resourceType": "source_code",
    "fileUrl": "https://github.com/hwchase17/langchain",
    "externalUrl": "https://github.com/hwchase17/langchain",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 620,
    "downloadsCount": 380,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.9,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.739Z",
    "updatedAt": "2026-08-11T07:41:54.739Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caa9",
    "title": "Node.js Event Loop Architecture Guide",
    "description": "In-depth video walkthrough of the Node.js event loop, call stack, microtask queue, libuv thread pool, and non-blocking I/O.",
    "thumbnail": "",
    "category": "Full Stack & Web Dev",
    "subCategory": "",
    "difficulty": "intermediate",
    "tags": [
      "nodejs",
      "event-loop",
      "javascript",
      "backend"
    ],
    "language": "English",
    "resourceType": "video",
    "fileUrl": "https://www.youtube.com/watch?v=8aGhZQkoFbQ",
    "externalUrl": "https://www.youtube.com/watch?v=8aGhZQkoFbQ",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 890,
    "downloadsCount": 410,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 5,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.739Z",
    "updatedAt": "2026-08-11T07:41:54.739Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caaa",
    "title": "Dynamic Programming & Backtracking Framework",
    "description": "Comprehensive video course on dynamic programming patterns, memoization, tabulation, state transitions, and backtracking.",
    "thumbnail": "",
    "category": "DSA & Algorithms",
    "subCategory": "",
    "difficulty": "advanced",
    "tags": [
      "dp",
      "dynamic-programming",
      "dsa",
      "algorithms"
    ],
    "language": "English",
    "resourceType": "video",
    "fileUrl": "https://www.youtube.com/watch?v=oBt53YbR9Kk",
    "externalUrl": "https://www.youtube.com/watch?v=oBt53YbR9Kk",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 950,
    "downloadsCount": 620,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 5,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.742Z",
    "updatedAt": "2026-08-11T07:41:54.742Z"
  },
  {
    "_id": "6a7ad242e3d2c3755532caab",
    "title": "Distributed Caching with Redis & Kafka Event Streaming",
    "description": "Architecture breakdown of distributed caching with Redis, pub/sub messaging, and event-driven microservices using Apache Kafka.",
    "thumbnail": "",
    "category": "System Design & DevOps",
    "subCategory": "",
    "difficulty": "advanced",
    "tags": [
      "redis",
      "kafka",
      "system-design",
      "microservices"
    ],
    "language": "English",
    "resourceType": "video",
    "fileUrl": "https://www.youtube.com/watch?v=b4b8ktEV4Bg",
    "externalUrl": "https://www.youtube.com/watch?v=b4b8ktEV4Bg",
    "codeContent": "",
    "codeLanguage": "javascript",
    "markdownContent": "",
    "duration": 0,
    "uploadedBy": "6a7acde1ad5446c461c3df75",
    "instructor": "",
    "views": 710,
    "downloadsCount": 390,
    "bookmarksCount": 0,
    "likes": [],
    "isFeatured": false,
    "isTrending": false,
    "averageRating": 4.9,
    "isPremium": false,
    "version": "1.0.0",
    "status": "published",
    "ratings": [],
    "comments": [],
    "__v": 0,
    "createdAt": "2026-08-11T07:41:54.742Z",
    "updatedAt": "2026-08-11T07:41:54.742Z"
  }
];

const getMockResources = async () => SEEDED_NOTES;
const getMockResourceById = async (id) => SEEDED_NOTES.find(r => r._id.toString() === id.toString()) || null;

module.exports = { SEEDED_NOTES, getMockResources, getMockResourceById };
